=== spryker/cms-block-storage/src/Spryker/Search/src/Spryker/Shared/Search/File/elasticsearch_index_definition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="indexes" type="Indexes"/>

    <xs:complexType name="Indexes">
        <xs:sequence>
            <xs:element type="Index" name="index" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Index">
        <xs:sequence>
            <xs:element type="IndexSettings" name="settings" minOccurs="0" maxOccurs="1"/>
            <xs:element type="Mapping" name="mapping" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="IndexSettings">
        <xs:sequence>
            <xs:element type="xs:integer" name="number_of_shards" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:integer" name="number_of_replicas" minOccurs="1" maxOccurs="1"/>
            <xs:element type="Analysis" name="analysis" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Analysis">
        <xs:sequence>
            <xs:element type="AnalysisSetting" name="analyzer" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="AnalysisSetting" name="char_filter" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="AnalysisSetting" name="tokenizer" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="AnalysisSetting" name="filter" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AnalysisSetting">
        <xs:sequence>
            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="Mapping">
        <xs:sequence>
            <xs:element type="Property" name="property" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="Property">
        <xs:sequence>
            <xs:element type="Properties" name="properties" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="PropertyAttribute" name="type" use="optional" default="string"/>
        <xs:attribute type="xs:boolean" name="include_in_all" use="optional" default="true"/>
        <xs:attribute type="IndexAttribute" name="index" use="optional" default="analyzed"/>
        <xs:attribute type="xs:string" name="analyzer" use="optional"/>
        <xs:anyAttribute processContents="skip"/>
    </xs:complexType>

    <xs:complexType name="Properties">
        <xs:sequence>
            <xs:element type="Property" name="property" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PropertyAttribute">
        <xs:restriction>
            <xs:enumeration value="string"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="long"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="binary"/>
            <xs:enumeration value="object"/>
            <xs:enumeration value="nested"/>
            <xs:enumeration value="geo_point"/>
            <xs:enumeration value="geo_shape"/>
            <xs:enumeration value="ip"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IndexAttribute">
        <xs:restriction>
            <xs:enumeration value="analyzed"/>
            <xs:enumeration value="not_analyzed"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== spryker/cms-block-storage/src/Spryker/Search/tests/Unit/Spryker/Zed/Search/Business/Model/Elastisearch/Definition/Fixtures/SingleIndex/test_index_definition.xml
<?xml version="1.0" encoding="utf-8"?>
<indexes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../../../../../../../src/Spryker/Shared/Search/File/elasticsearch_index_definition.xsd">

    <index name="foo">
        <settings>
            <number_of_shards>1</number_of_shards>
            <number_of_replicas>1</number_of_replicas>
            <analysis>
                <analyzer name="my_analyzer">
                    <type>standard</type>
                    <stopwords>_german_</stopwords>
                    <filter>standard</filter>
                    <filter>lowercase</filter>
                </analyzer>
            </analysis>
        </settings>
        <mapping name="page1">
            <property name="foo" analyzer="my_analyzer"/>
            <property name="bar">
                <properties>
                    <property name="baz"/>
                </properties>
            </property>
        </mapping>
        <mapping name="page2"/>
    </index>
</indexes>
